sudo: required
dist: trusty
group: edge

services:
  - docker
  - redis
language: python
python:
  - "3.6"
script:
  - make run_tests
  - bash <(curl -s https://codecov.io/bash)
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
