sudo: required
dist: trusty
group: edge

services:
  - docker
  - redis
language: python
python:
  - "3.6"
install:
  - pip install codecov
script:
  - make run_tests
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
after_success:
  - codecov
