sudo: required
dist: trusty
group: edge

services:
  - docker
  - redis
language: python
python:
  - "3.6"
install:
  - pip install codecov
script:
  - find . -name requirements.txt -type f -exec pip3 install -r {} \;
  - py.test -v -vv --cov-report term-missing --cov=./poseidon --cov=./api -c .coveragerc
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
after_success:
  - codecov
