https://github.com/cyberreboot/vent:
    elasticsearch:
        build: no
        start: no
    file_drop:
        build: yes
        start: yes
    network_tap:
        build: yes
        start: yes
    rabbitmq:
        build: yes
        start: yes
    redis:
        build: yes
        start: yes
    rmq_es_connector:
        build: no
        start: no
    rq_dashboard:
        build: yes
        start: yes
    rq_worker:
        build: yes
        start: yes
    syslog:
        build: yes
        start: yes
https://github.com/cyberreboot/poseidon:
    '@poseidon':
        build: yes
        start: yes
https://github.com/cyberreboot/vent-plugins:
    pcap_to_node_pcap:
        build: yes
https://github.com/lab41/poseidonml:
    nodeclassifier@eval:
        build: yes
