version: '2'

services:
  api:
    container_name: poseidon-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080
  notebooks:
    container_name: poseidon-notebooks
    build:
      context: .
      dockerfile: Dockerfile.notebooks
  monitor:
    container_name: poseidon-monitor
    build:
      context: .
      dockerfile: Dockerfile.monitor
    ports:
      - 8000
  main:
    container_name: poseidon
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - 8000
  storage:
    container_name: poseidon-storage
    build:
      context: .
      dockerfile: Dockerfile.storage
