version: '3.7'
services:
    redis:
        restart: always
        image: 'cyberreboot/redis:latest'
        volumes:
            - '${POSEIDON_PREFIX}/opt/redis:/data'
        networks:
            poseidon:
    rabbit:
        restart: always
        image: 'cyberreboot/rabbitmq:latest'
        ports:
            - '127.0.0.1:15672:15672'
            - '5672:5672'
        networks:
            poseidon:
                aliases:
                    - RABBIT_SERVER
                    - rabbitmq
                    - messenger
    network_tap:
        restart: always
        image: 'cyberreboot/network-tap:v0.11.0'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${POSEIDON_PREFIX}/opt/poseidon_files:/files'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
    crviz:
        restart: always
        image: 'cyberreboot/crviz:v0.3.18'
        ports:
            - '5001:5000'
        networks:
            poseidon:
    poseidon_api:
        build:
            context: api
            dockerfile: Dockerfile
        restart: always
        image: 'cyberreboot/poseidon-api:latest'
        ports:
            - '5000:8000'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
                aliases:
                    - poseidon-api
    poseidon:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        image: 'cyberreboot/poseidon:latest'
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
            - '${POSEIDON_PREFIX}/var/log/faucet:/var/log/faucet'
            - '${POSEIDON_PREFIX}/etc/faucet:/etc/faucet'
            - '${POSEIDON_PREFIX}/var/log/poseidon:/var/log/poseidon'
        networks:
            - poseidon
    workers:
        build:
            context: workers
            dockerfile: Dockerfile
        restart: always
        image: 'cyberreboot/poseidon-workers:latest'
        environment:
            PYTHONUNBUFFERED: '1'
            VOL_PREFIX: '${POSEIDON_PREFIX}'
        networks:
            - poseidon
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'

networks:
    poseidon:
