version: '3.7'
services:
    redis:
        restart: always
        image: 'cyberreboot/redis:latest'
        volumes:
            - '${POSEIDON_PREFIX}/opt/redis:/data'
        networks:
            poseidon:
    rabbit:
        restart: always
        image: 'cyberreboot/rabbitmq:latest'
        ports:
            - '127.0.0.1:15672:15672'
            - '5672:5672'
        networks:
            poseidon:
                aliases:
                    - RABBIT_SERVER
                    - rabbitmq
                    - messenger
    network_tap:
        restart: always
        image: 'cyberreboot/network-tap:v0.11.10'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${POSEIDON_PREFIX}/opt/poseidon_files:/files'
        environment:
            PYTHONUNBUFFERED: '1'
            KEEPIMAGES: '0'
        networks:
            poseidon:
    crviz:
        restart: always
        image: 'cyberreboot/crviz:v0.3.21'
        ports:
            - '5001:5000'
        networks:
            poseidon:
        depends_on:
            - poseidon
    poseidon_api:
        restart: always
        image: 'cyberreboot/poseidon-api:latest'
        ports:
            - '5000:8000'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
                aliases:
                    - poseidon-api
        depends_on:
            - poseidon
        build:
            context: api
            dockerfile: Dockerfile
    poseidon_certstrap:
        restart: on-failure
        image: 'cyberreboot/cyberreboot-certstrap:latest'
        build:
            context: certstrap
            dockerfile: Dockerfile
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
        command:
            - /opt/poseidon/local/faucetconfrpc
            - faucetconfrpc
    faucetconfrpc:
        restart: always
        image: 'cyberreboot/faucetconfrpc:v0.2'
        environment:
            PYTHONUNBUFFERED: '1'
        ports:
            - 59999
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon/local:/local'
            - /etc/faucet:/etc/faucet
        networks:
            poseidon:
        command:
            - --key=/local/faucetconfrpc/faucetconfrpc.key
            - --cert=/local/faucetconfrpc/faucetconfrpc.crt
            - --cacert=/local/faucetconfrpc/faucetconfrpc-ca.crt
            - --host=0.0.0.0
            - --config_dir=/etc/faucet
    poseidon:
        restart: always
        image: 'cyberreboot/poseidon:latest'
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
            - '${POSEIDON_PREFIX}/var/log/faucet:/var/log/faucet'
            - '${POSEIDON_PREFIX}/etc/faucet:/etc/faucet'
            - '${POSEIDON_PREFIX}/var/log/poseidon:/var/log/poseidon'
        networks:
            - poseidon
        depends_on:
            - rabbit
            - redis
            - faucetconfrpc
        build:
            context: .
            dockerfile: Dockerfile
    workers:
        restart: always
        image: 'cyberreboot/poseidon-workers:latest'
        environment:
            PYTHONUNBUFFERED: '1'
            KEEPIMAGES: '0'
            VOL_PREFIX: '${POSEIDON_PREFIX}'
            SWARM: '${POSEIDON_SWARM}'
        networks:
            - poseidon
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on:
            - poseidon
        build:
            context: workers
            dockerfile: Dockerfile
networks:
    poseidon:
        driver: overlay
