version: '3.7'
services:
    redis:
        restart: always
        image: 'cyberreboot/vent-redis:v0.10.1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/redis:/data'
        networks:
            poseidon:
    rabbit:
        restart: always
        image: 'cyberreboot/vent-rabbitmq:v0.10.1'
        ports:
            - '127.0.0.1:15672:15672'
            - '5672:5672'
        networks:
            poseidon:
                aliases:
                    - RABBIT_SERVER
                    - rabbitmq
                    - messenger
    network_tap:
        restart: always
        image: 'cyberreboot/vent-network-tap:v0.10.1'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${POSEIDON_PREFIX}/opt/vent_files:/files'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
                aliases:
                    - vent_ip
    crviz:
        restart: always
        image: 'cyberreboot/crviz:v0.3.17'
        ports:
            - '5001:5000'
        networks:
            poseidon:
    poseidon_api:
        restart: always
        image: 'cyberreboot/poseidon-api:master'
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - '5000:8000'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
                aliases:
                    - poseidon-api
    poseidon:
        restart: always
        image: 'cyberreboot/poseidon:master'
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
            - '${POSEIDON_PREFIX}/var/log/faucet:/var/log/faucet'
            - '${POSEIDON_PREFIX}/etc/faucet:/etc/faucet'
            - '${POSEIDON_PREFIX}/var/log/poseidon:/var/log/poseidon'
        networks:
            - poseidon
    workers:
        restart: always
        image: 'cyberreboot/poseidon-workers:latest'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            - poseidon
        volumes:
            - './workers.json:/app/workers.json'
            - '/definitions'
            - '/var/run/docker.sock:/var/run/docker.sock'

networks:
    poseidon:
