version: '2'

services:
  api:
    image: poseidon-api
    container_name: poseidon-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080
    env_file: poseidon.env
  periodically:
    image: poseidon-periodically
    container_name: poseidon-periodically
    build:
      context: .
      dockerfile: Dockerfile.periodically
    ports:
      - 8000
    env_file: poseidon.env
  docs:
    image: poseidon-docs
    container_name: poseidon-docs
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - 8000
    env_file: poseidon.env
  mock:
    image: mock-controller
    container_name: mock-controller
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - 8111
    env_file: poseidon.env
  monitor:
    depends_on:
      - api
    image: poseidon-monitor
    container_name: poseidon-monitor
    build:
      context: .
      dockerfile: Dockerfile.monitor
    ports:
      - 8000
    env_file: poseidon.env
  main:
    image: poseidon-main
    container_name: poseidon-main
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - 8000
    env_file: poseidon.env
  storageWorkaround:
    # http://www.diogogmt.com/running-mongodb-with-docker-and-compose/
    container_name: poseidon-storageWorkaround
    image: mongo
    volumes:
      - /data/db
    env_file: poseidon.env
  storage:
    container_name: poseidon-storage
    image: mongo
    volumes_from:
      - storageWorkaround
    ports:
      - 27017
    command: --smallfiles --rest --auth
    env_file: poseidon.env
