version: '2'

#  PORTS
#     api:                1111:8001
#     docs:               2222:8002
#     mock:               3333:8003
#     monitor:            4444:8004
#     main:               5555:8005
#     storage:            27017:27017
#     storage-interface:  28000:27000
#     periodically:       9999:8009

services:
  api:
    image: poseidon-api
    container_name: poseidon-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '1111:8001'
  docs:
    image: poseidon-docs
    container_name: poseidon-docs
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - '2222:8002'
  mock:
    image: mock-controller
    container_name: mock-controller
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - '3333:8003'
    environment:
      - ALLOW_ORIGIN = http://$DOCKER_IP:8003
      - DOCKER_IP
    links:
      - monitor:poseidon-monitor
  monitor:
    image: poseidon-monitor
    container_name: poseidon-monitor
    build:
      context: .
      dockerfile: Dockerfile.monitor
    ports:
      - '4444:8004'
    environment:
      - ALLOW_ORIGIN = http://$DOCKER_IP:1111
      - DOCKER_IP
    links:
      - api:poseidon-api
  main:
    image: poseidon-main
    container_name: poseidon-main
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - '5555:8005'
    environment:
      - DOCKER_IP
    links:
      - storage-interface:poseidon-storage-interface
  storageWorkaround:
    # http://www.diogogmt.com/running-mongodb-with-docker-and-compose/
    image: mongo
    container_name: poseidon-storageWorkaround
    volumes:
      - /data/db
  storage:
    image: mongo
    container_name: poseidon-storage
    ports:
      - '27017:27017'
    command: --smallfiles --rest --auth
    volumes_from:
      - storageWorkaround
    depends_on:
      - storageWorkaround
  storage-interface:
    image: poseidon-storage-interface
    container_name: poseidon-storage-interface
    build:
      context: .
      dockerfile: Dockerfile.storage-interface
    ports:
      - '28000:27000'
    environment:
      - ALLOW_ORIGIN=http://$DOCKER_IP:28000
      - DOCKER_IP
    links:
      - storage:poseidon-storage
    depends_on:
      - storageWorkaround
  periodically:
    image: poseidon-periodically
    container_name: poseidon-periodically
    build:
      context: .
      dockerfile: Dockerfile.periodically
    ports:
      - '9999:8009'
    environment:
      - DOCKER_IP
    links:
      - mock:mock-controller
      - monitor:poseidon-monitor
      - rabbit:poseidon-rabbit
  rabbit:
    image: rabbitmq:management
    container_name: poseidon-rabbit
    ports:
      - '15672:15672'
      - '5672:5672'
#
# -------------------- PLUGINS --------------------
#
  flowparser:
    image: flowparser
    container_name: flowparser
    build:
      context: ./plugins/features/flowparser/
      dockerfile: Dockerfile
    environment:
      - DOCKER_IP
    links:
      - rabbit:poseidon-rabbit
  ml-port-class:
    image: ml-port-class
    container_name: ml-port-class
    build:
      context: ./plugins/algorithms/port_classifier/
      dockerfile: Dockerfile
    environment:
      - DOCKER_IP
    links:
      - rabbit:poseidon-rabbit
