version: '3.7'
services:
    redis:
        restart: always
        image: 'iqtlabs/redis:v0.15.8'
        volumes:
            - '${POSEIDON_PREFIX}/opt/redis:/data'
        networks:
            poseidon:
    rabbit:
        restart: always
        image: 'iqtlabs/rabbitmq:v0.15.8'
        ports:
            - '127.0.0.1:15672:15672'
            - '5672:5672'
        networks:
            poseidon:
                aliases:
                    - RABBIT_SERVER
                    - rabbitmq
                    - messenger
    network_tap:
        restart: always
        image: 'iqtlabs/network_tap:v0.11.17'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${POSEIDON_PREFIX}/opt/poseidon_files:/files'
        environment:
            PYTHONUNBUFFERED: '1'
            KEEPIMAGES: '0'
        networks:
            poseidon:
    crviz:
        restart: always
        image: 'iqtlabs/crviz:v0.3.23'
        ports:
            - '5001:5000'
        networks:
            poseidon:
        depends_on:
            - poseidon
    poseidon_api:
        restart: always
        image: 'iqtlabs/poseidon-api:v0.15.8'
        ports:
            - '5000:8000'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
                aliases:
                    - poseidon-api
        depends_on:
            - poseidon
    poseidon:
        restart: always
        image: 'iqtlabs/poseidon:v0.15.8'
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
            - '${POSEIDON_PREFIX}/var/log/poseidon:/var/log/poseidon'
            - '${POSEIDON_PREFIX}/opt/faucetconfrpc:/certs'
        networks:
            - poseidon
        depends_on:
            - rabbit
            - redis
    workers:
        restart: always
        image: 'iqtlabs/poseidon-workers:v0.15.8'
        environment:
            PYTHONUNBUFFERED: '1'
            KEEPIMAGES: '0'
            VOL_PREFIX: '${POSEIDON_PREFIX}'
            SWARM: '${POSEIDON_SWARM}'
        networks:
            - poseidon
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on:
            - poseidon
networks:
    poseidon:
        driver: overlay
