version: '3.7'
services:
    redis:
        restart: always
        image: 'iqtlabs/redis:latest'
        volumes:
            - '${POSEIDON_PREFIX}/opt/redis:/data'
        networks:
            poseidon:
    rabbit:
        restart: always
        image: 'iqtlabs/rabbitmq:latest'
        ports:
            - '127.0.0.1:15672:15672'
            - '5672:5672'
        networks:
            poseidon:
                aliases:
                    - RABBIT_SERVER
                    - rabbitmq
                    - messenger
    network_tap:
        restart: always
        image: 'cyberreboot/network-tap:v0.11.12'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '${POSEIDON_PREFIX}/opt/poseidon_files:/files'
        environment:
            PYTHONUNBUFFERED: '1'
            KEEPIMAGES: '0'
        networks:
            poseidon:
    crviz:
        restart: always
        image: 'cyberreboot/crviz:v0.3.22'
        ports:
            - '5001:5000'
        networks:
            poseidon:
        depends_on:
            - poseidon
    poseidon_api:
        restart: always
        image: 'iqtlabs/poseidon-api:latest'
        ports:
            - '5000:8000'
        environment:
            PYTHONUNBUFFERED: '1'
        networks:
            poseidon:
                aliases:
                    - poseidon-api
        depends_on:
            - poseidon
        build:
            context: api
            dockerfile: Dockerfile
    poseidon:
        restart: always
        image: 'iqtlabs/poseidon:latest'
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/poseidon:/opt/poseidon'
            - '${POSEIDON_PREFIX}/var/log/poseidon:/var/log/poseidon'
            - '${POSEIDON_PREFIX}/opt/poseidon/local:/local'
        networks:
            - poseidon
        depends_on:
            - rabbit
            - redis
        build:
            context: .
            dockerfile: Dockerfile
    workers:
        restart: always
        image: 'iqtlabs/poseidon-workers:latest'
        environment:
            PYTHONUNBUFFERED: '1'
            KEEPIMAGES: '0'
            VOL_PREFIX: '${POSEIDON_PREFIX}'
            SWARM: '${POSEIDON_SWARM}'
        networks:
            - poseidon
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on:
            - poseidon
        build:
            context: workers
            dockerfile: Dockerfile
networks:
    poseidon:
        driver: overlay
