version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run; chmod -R 777 /usr/local/lib/python3.6/
      - run: pip install -r requirements.txt
      - run: pip install pytest==2.9.1
      - run: py.test -v --cov=poseidon --cov-report term-missing
      - run: bash <(curl -s https://codecov.io/bash) -t 992b90e5-a0b2-45c5-b9d5-3baddc184162
