version: '3.7'
services:
    rabbitmq_adapter:
        restart: always
        image: 'faucet/event-adapter-rabbitmq:1.9.32'
        volumes:
            - '${POSEIDON_PREFIX}/var/run/faucet:/var/run/faucet'
        environment:
            FAUCET_EVENT_SOCK: '1'
            FA_RABBIT_HOST: 'rabbit'
            FA_RABBIT_PORT: '${FA_RABBIT_PORT}'
            FA_RABBIT_EXCHANGE: '${FA_RABBIT_EXCHANGE}'
            FA_RABBIT_EXCHANGE_TYPE: '${FA_RABBIT_EXCHANGE_TYPE}'
            FA_RABBIT_ROUTING_KEY: '${FA_RABBIT_ROUTING_KEY}'
        networks:
            - poseidon
networks:
    poseidon:
