version: '3.7'
services:
    rabbitmq_adapter:
        restart: always
        image: 'faucet/event-adapter-rabbitmq:1.9.47'
        volumes:
            - '${POSEIDON_PREFIX}/var/run/faucet:/var/run/faucet'
        environment:
            FAUCET_EVENT_SOCK: '1'
            FA_RABBIT_HOST: 'rabbit'
            FA_RABBIT_PORT: '${FA_RABBIT_PORT}'
            FA_RABBIT_EXCHANGE: '${FA_RABBIT_EXCHANGE}'
            FA_RABBIT_EXCHANGE_TYPE: '${FA_RABBIT_EXCHANGE_TYPE}'
            FA_RABBIT_ROUTING_KEY: '${FA_RABBIT_ROUTING_KEY}'
        networks:
            - poseidon
    faucet_certstrap:
        restart: on-failure
        image: 'iqtlabs/faucet-certstrap:latest'
        build:
            context: helpers/faucet/certstrap
            dockerfile: Dockerfile
        volumes:
            - '${POSEIDON_PREFIX}/opt/faucetconfrpc:/opt/faucetconfrpc'
        command:
            - /opt/faucetconfrpc
            - faucetconfrpc
    faucetconfrpc:
        restart: always
        image: 'iqtlabs/faucetconfrpc:v0.14'
        environment:
            PYTHONUNBUFFERED: '1'
        volumes:
            - '${POSEIDON_PREFIX}/opt/faucetconfrpc:/certs'
            - /etc/faucet:/etc/faucet
        ports:
            - '127.0.0.1:59999:59999'
        networks:
            - poseidon
        command:
            - --key=/certs/faucetconfrpc.key
            - --cert=/certs/faucetconfrpc.crt
            - --cacert=/certs/faucetconfrpc-ca.crt
            - --host=0.0.0.0
            - --config_dir=/etc/faucet
networks:
    poseidon:
        driver: overlay
