version: '3.7'
services:
    rabbitmq_adapter:
        restart: always
        image: 'faucet/event-adapter-rabbitmq:1.9.42'
        volumes:
            - '${POSEIDON_PREFIX}/var/run/faucet:/var/run/faucet'
        environment:
            FAUCET_EVENT_SOCK: '1'
            FA_RABBIT_HOST: 'rabbit'
            FA_RABBIT_PORT: '${FA_RABBIT_PORT}'
            FA_RABBIT_EXCHANGE: '${FA_RABBIT_EXCHANGE}'
            FA_RABBIT_EXCHANGE_TYPE: '${FA_RABBIT_EXCHANGE_TYPE}'
            FA_RABBIT_ROUTING_KEY: '${FA_RABBIT_ROUTING_KEY}'
        networks:
            - poseidon
    faucetagent_adapter:
        restart: "no"
        image: 'faucet/event-adapter-faucetagent:1.9.42'
        ports:
            - '10161:10161'
        volumes:
            - '${POSEIDON_PREFIX}/opt/faucetagent/certs:/opt/faucetagent/certs'
            - '${POSEIDON_PREFIX}/etc/faucet:/etc/faucet'
networks:
    poseidon:
        driver: overlay
